name: supabase_auth_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/supabase_auth_client/**"
      - ".github/workflows/supabase_auth_client.yaml"
    branches:
      - master
  
jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.0.2
      working_directory: packages/supabase_auth_client
      coverage_excludes: "lib/src/generated/*.dart"